name: build and publish dockerfile
on:
  push:
    branches: ["main", "ci/docker"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: "jli198"
        password: ${{ secrets.BLUEPRINT_ADMIN_BACKEND }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/stevensblueprint/blueprint_admin_backend:${{ github.sha }}
          ghcr.io/stevensblueprint/blueprint_admin_backend:latest